### ISSUE TITLE
TODO Problema ClaseFacultate

### ISSUE THREAD

**Issue by stefan-sava** [stefan-sava/JavaAndGitLearning#4]
TODO la probClaseFacultate

- [x] 1-> adaugati un student

- [x] 2-> adaugati un cadru didactic

- [x] 3-> adaugati un angajat, personal nedidactic 

- [ ] 4-> stergeti un angajat (cautati-l dupa nume si prenume, citite de la tastatura)

- [ ] 5-> stergeti un student (cautati-l dupa nume si prenume, citite de la tastatura)

- [ ] 6-> adaugati o nota pentru un student (cititi cursul, numele studentului si nota de la tastatura)

- [ ] 7-> modificati o nota pentru un student (cititi cursul, numele studentului si nota de la tastatura)

- [ ] 8-> adaugati un curs nou

- [ ] 9-> salvare in fisier
